
# SEO
title: Swiss Jekyll Theme
description: A bold typographic theme inspired by Swiss design.

# social
social_link: twitter
social_username: broccolini
github_repo: athena # the GitHub repo name for your project
github_username: broccolini
theme_color: black

# Theme
remote_theme: 'internet-de-france/swiss'
baseurl: '/lucasvazq'

# Defaults

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      category_name: ""
  -
    scope:
      path: ""
      type: "posts"
    values:
      categories: ""

# Stastic UI
remote_theme_layouts: 
  - ""
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble

theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow


